name: flutter_foodapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^3.0.0
  cloud_firestore: ^5.2.1
  shared_preferences: ^2.3.1
  firebase_auth: ^5.1.4
  image_picker: ^1.1.2
  provider: ^6.1.2
  fl_chart: ^0.68.0

flutter:
  uses-material-design: true
