// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv2j2sv9yuSjmJR6POal1Ia9MKphj7WZQ',
    appId: '1:694857150571:web:0dba93eed0d9990bf1c12e',
    messagingSenderId: '694857150571',
    projectId: 'foodapp-eb833',
    authDomain: 'foodapp-eb833.firebaseapp.com',
    storageBucket: 'foodapp-eb833.appspot.com',
    measurementId: 'G-9VXVR9NS4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmYxNCd-pY_k0A4MQjo6gi3Sa4jkOhsJk',
    appId: '1:694857150571:android:a3eed28b5dd3a000f1c12e',
    messagingSenderId: '694857150571',
    projectId: 'foodapp-eb833',
    storageBucket: 'foodapp-eb833.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH8vH0kd0gwj_HZmY7VaS8mnCzstkcOR4',
    appId: '1:694857150571:ios:0c2950b113a4fe13f1c12e',
    messagingSenderId: '694857150571',
    projectId: 'foodapp-eb833',
    storageBucket: 'foodapp-eb833.appspot.com',
    iosBundleId: 'com.example.flutterFoodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH8vH0kd0gwj_HZmY7VaS8mnCzstkcOR4',
    appId: '1:694857150571:ios:0c2950b113a4fe13f1c12e',
    messagingSenderId: '694857150571',
    projectId: 'foodapp-eb833',
    storageBucket: 'foodapp-eb833.appspot.com',
    iosBundleId: 'com.example.flutterFoodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv2j2sv9yuSjmJR6POal1Ia9MKphj7WZQ',
    appId: '1:694857150571:web:e2feff8630da532cf1c12e',
    messagingSenderId: '694857150571',
    projectId: 'foodapp-eb833',
    authDomain: 'foodapp-eb833.firebaseapp.com',
    storageBucket: 'foodapp-eb833.appspot.com',
    measurementId: 'G-QG4CJT8130',
  );
}
